CREATE TABLE CURRENCY_RATE (
    id               NUMBER(19) not NULL primary key,
    CURRENCY_ID      VARCHAR2(3)  not NULL CONSTRAINT CURRENCY_RATE_FK_CODE references CURRENCY_DICTIONARY(ID) on delete cascade,
    CURRENCY_BID     NUMBER(14, 2) not null,
    CURRENCY_ASK     NUMBER(14, 2) not null,
    UPLOAD_DATE      DATE not null,
    VERSION          NUMBER(19) DEFAULT 0 NOT NULL,
    MODIFIED_ON      DATE NOT null
);

COMMENT ON COLUMN CURRENCY_RATE.CURRENCY_ID IS 'CURRENCY CODE';
COMMENT ON COLUMN CURRENCY_RATE.CURRENCY_BID IS 'BUY PRICE';
COMMENT ON COLUMN CURRENCY_RATE.CURRENCY_ASK IS 'SELL PRICE';



create
    sequence CURRENCY_RATE_SEQ
    maxvalue 9999999999
    start with 1
    increment by 1
    cache 20;